### ISSUE TITLE
同步至官方文件的版本

### ISSUE THREAD

**Issue by jigsawye** [laravel-taiwan/docs#149]
想問一下能夠更新到目前原文文件的版本嗎？我上次在用 Envoy 的 Slack Webhook 一直搞不定，結果原來是原文文件已經更新寫法了，可是中文文件還是舊的，花了不少時間。

如果不行的話還是像 #146 直接拉 laravel.com 的文件下來翻譯後追加到中文檔案上呢？

**Comment by chentsulin** [comment]
上一次跟 upstream 的 merge 是 #138
我們這邊大概落後快兩個月

我不太建議脫離 git 的控制直接手動改，這樣 git 不知道英文還是中文是新的，以後就必須完全人工的比對

我盡量這禮拜找時間更新一下好了，這中間也是要去手動排除衝突
不過看似沒有更簡單的方式？

**Comment by jigsawye** [comment]
我對 Git 的指令也沒有了解得很透徹，據我所知也是要手動修正 conflict，這部份可能要看有沒有其他人有更好的解決方式。
現階段就再麻煩你了，我這邊能協助的部分就是幫忙翻譯原文文文件！
