### ISSUE TITLE
共同翻译 Laravel 5.1 文档

### ISSUE THREAD

**Issue by artiship** [laravel-taiwan/docs#178]
大家好,

我是大陆的 Laravel 爱好者，我也在组织大家一起翻译 Laravel 5.1 文档，同时我也看到你们，来自台湾的伙伴们也在做同样的事情。

虽然简体中文与繁体中文的翻译稍有差别，但是有很多翻译只需修改就可以重用，中文的译法也是相通的，因此我想联合大家，大陆与台湾的伙伴们共同翻译，互通有无，一起学习。

协作沟通最为重要，我们除了使用 GitHub 以外，还使用了腾讯公司的 QQ 作为即时通讯软件，所以我想台湾的伙伴是否也可以使用，然后大家可以加到一个群里面，方便即时沟通问题。

我们 GitHub 地址 https://github.com/laragirl/docs

**Comment by appleboy** [comment]
@artiship 很高興你提出這想法，但是不知道你有跟 https://github.com/laravel-china/docs 他們溝通過嗎？畢竟你現在做的翻譯，他們也正在翻喔

https://github.com/laravel-china/docs

**Comment by artiship** [comment]
@appleboy 

我知道这个网站，不过 5.1 版本的文档，他们似乎还未开展，进展较缓慢，没有人在推动这件事情。我也同样愿意同他们一起翻译，翻译是件很花时间的事情，不需要做重复的工作，参与的人多，可以更早地将文档翻译出来，这个是我想要的结果。

甚至我觉得我们翻译的结果，为什么不直接放到 Laravel 的官网上，Laravel 为什么不支持多语言文档呢？这个建议我也提交到 laravel/docs 上了。

我希望文档早些翻译出来，也希望通过做这件事情，让大家有更多沟通，一起学习新知。

**Comment by appleboy** [comment]
可否發到 phphub 論壇上我們一起討論呢？

https://phphub.org/

那邊會有蠻多人可以加入翻譯，把你的想法轉到那邊去，我們去那邊討論。畢竟這邊中國朋友們不會看到。

**Comment by artiship** [comment]
看过你们的翻译，我有些感慨，大陆与台湾才几十年时间，简体中文与繁体中文已然有很大差异，例如，我们叫文档的，你们称文件，我们叫对象的，你们称物件，我们叫哈希的，你们称杂凑，我们叫程序的，你们称程式，最有意思的是，我叫缓存的，你们称快取，照此下去，岂不越发隔离。

**Comment by artiship** [comment]
我已经在上面发过帖了，还有另外一个网站 golaravel.com，我也发过帖了

https://phphub.org/topics/998
http://wenda.golaravel.com/question/1124

论坛是一种沟通方式，即时通信也是需要的，我建了 QQ 群 297473872

**Comment by artiship** [comment]
@appleboy https://github.com/laravel/docs/pull/1623
