### ISSUE TITLE
Broken of API document link in menu

### ISSUE THREAD

**Issue by chentsulin** [laravel-taiwan/docs#184]
should links to `http://laravel.com/api/5.1/` rather than `http://laravel.tw/api/5.1`

**Comment by jigsawye** [comment]
這個問題應該要修改 [laravel.tw](https://github.com/laravel-taiwan/laravel.tw) 的 Source Code，
我想到最快的解法就是在 Route 多寫一個 Redircet

**Comment by chentsulin** [comment]
:+1: 
他 api 是 sami build 出來的
https://github.com/laravel/laravel.com/blob/master/build/api.sh

寫個 route redirect 是個好解法

**Comment by jigsawye** [comment]
不知道把 [documentation.md](https://github.com/laravel-taiwan/docs/blob/5.1/documentation.md) 的
`- [API 文件](/api/{{version}})`
改成
`- [API 文件](http://laravel.com/api/{{version}})`
行不行

**Comment by chentsulin** [comment]
理論上可行

**Comment by chentsulin** [comment]
Fixed. @jigsawye good idea!
