### ISSUE TITLE
blade.md 的斜體轉換不正確

### ISSUE THREAD

**Issue by jigsawye** [laravel-taiwan/docs#187]
http://laravel.tw/docs/5.1/blade#template-inheritance

文件上的 `_模板繼承_` 沒有被正確轉換成斜體：
![2015-07-07 1 06 49](https://cloud.githubusercontent.com/assets/8567270/8539094/5916ef78-24a9-11e5-8fa3-cf07f9c2d1fb.png)

Github 的 preview 正常：
![2015-07-07 1 07 15](https://cloud.githubusercontent.com/assets/8567270/8539117/9c942fea-24a9-11e5-94ac-2982260590e9.png)

原始內容：
![2015-07-07 1 07 42](https://cloud.githubusercontent.com/assets/8567270/8539098/5cae3af6-24a9-11e5-9a25-747a4293c5ab.png)

**Comment by storyn26383** [comment]
如果把 `底線` 換成 `星號` 可解決此問題，如下：

    使用 Blade 模板的兩個主要優點為_模板繼承_與_區塊_。

    使用 Blade 模板的兩個主要優點為*模板繼承*與*區塊*。
