### ISSUE TITLE
authentication.md 文件更新後尚未翻譯的部分。

### ISSUE THREAD

**Issue by neighborhood999** [laravel-taiwan/docs#194]
Laravel 文件 [認證](http://laravel.tw/docs/5.1/authentication) 的 **Authentication Throttling** 部分尚未翻譯。

> -
If you are using Laravel's built-in AuthController class, the Illuminate\Foundation\Auth\ThrottlesLogins trait may be used to throttle login attempts to your application. By default, the user will not be able to login for one minute if they fail to provide the correct credentials after several attempts. The throttling is unique to the user's username / e-mail address and their IP address:
....

**Comment by chentsulin** [comment]
Done
