### ISSUE TITLE
 Laravel 中文文件翻譯對照表與規範

### ISSUE THREAD

**Issue by jigsawye** [laravel-taiwan/docs#259]
# Laravel 中文文件翻譯對照表與規範
## 前言

很慶幸的，有各位熱心的夥伴參與翻譯，其實就算是單人翻譯的狀況，常常會發生有些專有名詞或者是格式上前後不一的狀況。所以開了一個 issue 專門記錄這些規範以及參考的翻譯對照表。有些是我個人的一些想法，如果夥伴們有其他的意見跟想法歡迎提出來討論。
關於專有名詞翻譯的部分，我能理解部分夥伴會覺得就保留英文即可，但我會希望文件也類似於中文翻譯書般。這樣做是因為對於初學者來說不會因為滿滿的英文專有名詞而產生抗拒。當然前提是在於中文的翻譯是否能夠達意，這部分建議參考對岸的一些翻譯，有時候比我們的還直觀。但對於像 Laravel、Composer 等是名字、指令等就不強求要中文對照，這類不會有統一翻法更不容易從翻譯中知道用意的，就保留英文即可。如果不清楚該怎麼翻才好也可以留著與大家討論。

下方的規範會隨著校對時一起更新，謝謝大家的參與。
## 規範
- 請參考[中文排版指南](https://github.com/sparanoid/chinese-copywriting-guidelines)與以下規範：
- 英文與中文間請保持一個空白（與標點符號間則不用），才不會跟中文黏在一起，不容易閱讀。
- 請使用全形標點符號。
- 檢查譯文與原文的總行數是否相符。
- 請閱讀 Markdown 語法，請勿讓語法錯亂。
- 原文中的雙引號（`" "`）請代換成中文的引號（`「」`）。
- 請勿添加譯註或是其他不存在於原文的內容。
### A
- Aggregate 聚合
- Array 陣列
- Artisan (指令，不翻)
- Argument 參數
- Assets 資源檔
- Authentication 認證
- Authorization 授權
- Adapter 接口
- Ability 權限
### B
- Blade (Laravel 的模板引擎，不翻)
- Bundle (上一代的 package 名稱，不翻)
- Binding 綁定
- Builder 建構器
### C
- Cache 快取
- Call 呼叫
- Callback 回呼
- Class 類別
- CLI 指令列介面
- Command 指令
- Command Line 指令列
- Component 元件
- Console 終端
- Context 情境、上下文
- Controller 控制器
- Controller Action 控制器行為
- constructor 建構子
- Cookie (不翻)
- Contract (不翻)
- Composer (公定名稱，不翻)
- Credentials 憑證
- Closure 閉包
- Configuration 設定
- Chain 鏈結
### D
- Database-Transactions  資料庫交易
- Deferred Providers 緩載提供者
- Driver 驅動
- Dependency 依賴
- Dependency Injection 依賴注入
- Directive 指令
### E
- Event 事件
- Extend 繼承
- Extension 擴充功能
- Eloquent (不翻)
- Exception 例外
### F
- Facades (不翻)
- Framework 框架
- Filter 篩選器
- Form 表單
- Function 函式
### G
- Guide 導引
- Generator 產生器
### H
- Helper 輔助函式
- Hash 雜湊
- Homestead (不翻)
- Header 標頭
- Hook 掛勾
### I
- Instance 實例
- inheritance 繼承
- implements 實作
### J
- Job 任務
### K
- Key 鍵
### L
- Laravel (不翻)
- Listener 監聽器
- Library 函式庫
### M
- Method 方法
- Migration 遷移
- Model 模型
- Middleware 中介層
### N
- Namespace 命名空間
### O
- Object 物件
### P
- Package 套件
- Packagist (公定名稱，不翻)
- Provider 提供者
- Prefix 前綴
- Presenter 呈現器
- Pipeline 管線
- Policy 原則
### Q
- Queue 隊列
- Query Builder查詢產生器
### R
- Route / Routing 路由
- Request 請求
- Response 回應
- Resolved 解析
- Repository 儲存庫
- Redirect 重導
- (Database's) Rollback 還原
### S
- Schema 結構
- Service 服務
- Service Container 服務容器
- Service Providers 服務提供者
- Session (不翻)
- Seed 資料填充
- Scheduler 排程器
- Signature 用法
### T
- Task 任務
- Tag 標籤
- Table 資料表
- Templates 模板
- Terminal 終端機
- Token 標記
- Timestamps 時間戳記
- Type-hint 型別提示
- Trait (不翻)
- Ternary statement 三元運算子
- Throw (Exception) 拋出（例外）
### V
- Vagrant (不翻)
- Vagrant Box (不翻)
- View 視圖
- Vendor 供應商
- View Composer 視圖組件
### W
- Workbench (指令，不翻)
- Webhooks (不翻)
- Word Factor 加密係數

**Comment by neighborhood999** [comment]
:+1:

**Comment by appleboy** [comment]
要不要放一份在 source code 內，也許會比較好

**Comment by jigsawye** [comment]
@appleboy 對應的部分還一些模糊地帶，等整理完統一之後再放進去 :+1:

**Comment by appleboy** [comment]
:+1: Good Job

**Comment by appleboy** [comment]
原本要開類似這 issue，剛好看到，那就不用開了

根據 https://github.com/laravel-taiwan/docs/pull/297#discussion_r48322033

大家來重新定義哪些名詞需要翻譯，哪些不用

我自己看了一下感覺，很多都不想翻譯成中文 XDDD

cc @jigsawye @farrrr @chentsulin @jasteralan

**Comment by jigsawye** [comment]
`Collection`  `Controller` `View` `Model` `Request` `Response` `Route` 
這些太常用到了，類別名稱也是英文
`Service Container` `Service Provider` 感覺也可以不用翻
資料型別，像是 `Array` `String` 我也覺得可以不用翻
@appleboy 完了感覺很多都不想翻XD

**Comment by jigsawye** [comment]
應該說在框架內舉凡 `make:` 系列指令，或是內建已有的資料夾跟類別，都是英文的，註解也是英文的
翻成中文有時反而不知道在指什麼東西

**Comment by appleboy** [comment]
我建議可以直接把該文件找要翻譯的可能會少於不要翻的 XD

**Comment by jasteralan** [comment]
陣列 字串很常見，翻了也不會難懂吧 XD

感覺很多 laravel 裡面用到的名詞可以不用翻，不過還蠻多 XD
Builder, Driver, Helper, Job, Listener, Migration,Model
Pipeline, Policy, Queue, Repository, Rollback, Schema....

**Comment by jigsawye** [comment]
我覺得就像 @chentsulin 翻的 [redux 中文文件](http://chentsulin.github.io/redux/docs/basics/Actions.html)那樣
保留一些在開發時很常見到的英文

**Comment by jigsawye** [comment]
@jasteralan 因為我覺得有時很長一串中文會喪失焦點，像 Array 或 String 第一眼就可以看到型別XD

不過還有個問題是，像是 `Controller` 若保留原文
那像是 `RESTful Resource Controllers` 這樣的名詞該如何翻？
`RESTful 資源 Controllers` 還是保留原文？

**Comment by appleboy** [comment]
RESTful Resource Controllers 我覺得這邊可以剪寫成 RESTful 就可以了，至少我們工程師溝通，有人會講 RESTful Resource Controllers? ＸＤ

**Comment by jigsawye** [comment]
@appleboy 不無道理，我覺得一些英文名詞在翻譯時可以加上中文修飾
像是：`validation` => **資料`驗證`**、`authentication` => **身份`認證`**

**Comment by appleboy** [comment]
@jigsawye 非常好啊，有些英文沒表達的，但是我們看起來就是這意思，就可直接翻成大家看得懂的中文。先把 5.1 的翻譯先搬過來，之後開個 issue 來潤飾每篇翻譯。

**Comment by jigsawye** [comment]
@appleboy OK！再麻煩各位校稿了 cc @chentsulin

**Comment by taichunmin** [comment]
我目前正在翻譯 5.5 的 `views.md`
contract 要翻譯嗎XD

**Comment by neighborhood999** [comment]
@taichunmin 我覺得可以不用翻，翻譯後反而有點怪～

**Comment by taichunmin** [comment]
那要不要補上去上面的清單中呢？

**Comment by flamerecca** [comment]
Testing 的 `Stub` 是否以後確定翻譯成 `範本`？

**Comment by Nationalcat** [comment]
GitHub 終於開放討論區了，所以我將規範與專有名詞對照表建置到 [wiki](https://github.com/laravel-taiwan/docs/wiki) 上，專有名詞的定義就到討論區依個案開串討論吧。
