### ISSUE TITLE
已完成文件一覽 #c2d46a (Dec 12, 2015)

### ISSUE THREAD

**Issue by jigsawye** [laravel-taiwan/docs#269]
記錄已完全中文化的文件，根據對照表重新校稿則留至下一階段。

部分 diff: https://github.com/laravel-taiwan/docs/pull/263/files

- [x] artisan.md
- [x] authentication.md
- [x] authorization.md
- [x] billing.md
- [x] blade.md
- [x] cache.md
- [x] collections.md
- [x] container.md
- [x] contracts.md
- [x] contributions.md
- [x] controllers.md
- [x] database.md
- [x] documentation.md
- [x] elixir.md
- [x] eloquent-collections.md
- [x] eloquent-mutators.md
- [x] eloquent-relationships.md
- [x] eloquent-serialization.md
- [x] eloquent.md
- [x] encryption.md
- [x] envoy.md
- [x] errors.md
- [x] events.md
- [x] facades.md
- [x] filesystem.md
- [x] hashing.md
- [x] helpers.md
- [x] homestead.md
- [x] installation.md
- [x] lifecycle.md
- [x] localization.md
- [x] mail.md
- [x] middleware.md
- [x] migrations.md
- [x] packages.md
- [x] pagination.md
- [x] providers.md
- [x] queries.md
- [x] queues.md
- [x] quickstart-intermediate.md
- [x] quickstart.md
- [x] redis.md
- [x] releases.md
- [x] requests.md
- [x] responses.md
- [x] routing.md
- [x] scheduling.md
- [x] seeding.md
- [x] session.md
- [x] structure.md
- [x] testing.md
- [x] upgrade.md
- [x] validation.md
- [x] views.md

**Comment by chentsulin** [comment]
@jigsawye :+1: 好強大的效率

**Comment by jigsawye** [comment]
@chentsulin 送最後的 PR 了，上面的 PR merge 完就翻完 5.1 文件了 :sleepy:

**Comment by odie1111** [comment]
各位大大辛苦了！

Evan Ye <notifications@github.com> 於 2015年12月15日 週二 上午11:11寫道：

**Comment by jigsawye** [comment]
Done!

**Comment by chentsulin** [comment]
:tada:
